Web Dev Lesson -- Tailwind Assignment
skillify-ca/skillify-web pull request #906
Opened 2023-03-07 02:07 UTC by LuckyHariharan

Hi Raveen, I put up a simple assignment for students to lock-in their tailwind css knowledge. Regarding the   `const assignmentId = "2cf9156a-4f6f-452d-b09a-2c54f19a7b40";` , how do I create an id for this assignment!

Ty in advance for any feedback!

2023-03-07 02:13 UTC, vithushan19 approved these changes

2023-03-07 02:21 UTC, vithushan19 approved these changes
this looks great nice work!

2023-03-13 15:31 UTC, iamnotreddy requested changes
Nice work on this assignment. The grid vs. flex explanation was much clearer than the first time. Great interactive exercise for students to learn tailwind.

Couple things before approving:
- make sure you generate a new assignment ID in hasura and paste it in the server side props
- you're missing a template section. Fork this [template](https://codesandbox.io/s/react-typescript-tailwind-template-6t0ywc) to create a starting point for the assignment. Maybe you want to have the student start with unstyled text and / or other HTML elements so it's clearer to them that they need to restyle them using tailwind. Once you save this link, you can put it inside the template sub-component

2023-03-13 15:31 UTC, iamnotreddy commented on pages/studentPortal/web/React/assignments/tailwindAssignment.tsx
> +          description: "Setup TailwindCSS using Play CDN, follow step one",
let's abstract the tailwind setup from this assignment,

you can fork this [template](https://codesandbox.io/s/react-typescript-tailwind-template-6t0ywc) then setup the assignment:

2023-03-13 15:31 UTC, iamnotreddy commented on pages/studentPortal/web/React/assignments/tailwindAssignment.tsx
> +  const assignmentId = "2cf9156a-4f6f-452d-b09a-2c54f19a7b40";
this assignmentId is the same as the other assignment

create a new assignment in the coding_assignments table and name it Tailwind Assignment. You can then paste the ID that hasura generates over here

2023-03-14 13:07 UTC, iamnotreddy approved these changes
nice

2023-03-14 13:33 UTC, merged