Max Selection
skillify-ca/skillify-web pull request #924
Opened 2023-03-24 23:22 UTC by LuckyHariharan

In this PR I modified SkillSelections.tsx to:

- Add a maxSelections prop which disallows the user from over-selcting
- If maxSelections == 1, the user can freely click any option and it will automatically change for them

2023-03-24 23:23 UTC, LuckyHariharan commented on components/resources/quizzes/shared/SkillSelections.tsx
> +    } else if (maxSelections === 1) {
edge case if maxSelections === 1

2023-03-24 23:23 UTC, LuckyHariharan commented on components/resources/quizzes/shared/SkillSelections.tsx
> +  useEffect(() => {
useEffect to clear the selections. @jimip85 you might find this helpful for your list datastrcture that captures all the users selections.

2023-03-24 23:54 UTC, LuckyHariharan commented
Had a couple bugs because I was a little too ambitious in this PR and tried to keep track of each pages preferences. Will talk to Jimi to pair on that problem instead.

2023-03-25 15:51 UTC, vithushan19 reviewed
Looking good. Can we add some tests

2023-03-25 15:51 UTC, vithushan19 commented on components/resources/quizzes/shared/SkillSelections.tsx
> +  industries: string[];
This shouldn't be in shared, this is specific to your quiz not all quizzes

2023-03-25 15:51 UTC, vithushan19 commented on components/resources/quizzes/shared/SkillSelections.tsx
> +  useEffect(() => {
Nice

2023-03-25 15:51 UTC, vithushan19 commented on components/resources/quizzes/shared/SkillSelections.tsx
> +    setSelected(quizObject[page] || []);
Nice!

2023-03-25 15:51 UTC, vithushan19 commented on components/resources/quizzes/shared/SkillSelections.tsx
> +      setSelected([selection]);
Amazing

2023-03-25 15:51 UTC, vithushan19 commented on pages/career-quiz.tsx
> +    industries: [],
This is fine here, but I think we don't have to specify this type in the shared component with these exact keys.

In the shared component you can use the Record type in typescript.

Search for other uses of the Record type in our repo

2023-03-25 15:51 UTC, vithushan19 commented on components/resources/quizzes/shared/SkillSelections.tsx
> +  industries: string[];
I think the type of quiz object should be a record of string to an array of some other type.

Try to figure out how record can help, if you get stuck we can chat this week

2023-03-25 15:51 UTC, vithushan19 commented on components/resources/quizzes/shared/SkillSelections.tsx
> +      setSelected([selection]);
Can we test this somehow? Not sure if this is easy to test with jest

2023-03-25 15:51 UTC, vithushan19 commented on components/resources/quizzes/shared/SkillSelections.tsx
> +      setSelected([selection]);
Or a testing library

2023-03-31 08:50 UTC, vithushan19 requested changes
this would be a good change to get in if you can address earlier comments. @LuckyHariharan

2023-04-11 18:16 UTC, jimip85 commented on components/resources/quizzes/careerQuiz/career-quiz.tsx
Awesome!

2023-04-12 09:57 UTC, vithushan19 requested changes
looking really good! nice strong PR. clean and readable code, great comments. Keep it up!

2023-04-12 09:57 UTC, vithushan19 commented on components/resources/quizzes/careerQuiz/career-quiz.tsx
> +      progress: quizData.questions.length,
I'm pretty sure this useEffect is not needed, and you can just use this object in the state initializer at line 38

2023-04-12 09:57 UTC, vithushan19 commented on components/resources/quizzes/careerQuiz/career-quiz.tsx
> +      // Set all other options to false and set the selected option to true
great comment!

2023-04-12 09:57 UTC, vithushan19 commented on components/resources/quizzes/careerQuiz/career-quiz.tsx
>      const selectedQuizOption = quizViewState.questions.map((question) => ({
I might wrap the rest of this code in an else statement, if that makes sense to you.

2023-04-12 09:57 UTC, vithushan19 commented on components/resources/quizzes/shared/Progress.tsx
> +        style={{ width: `${index >= 0 ? (index * 100) / progress : 100}%` }}
I think all this calculation should be happening in the view state, not in the component. `progress` should be a percentage that you just pass in. This component shouldnt need to know the current index. You're just passing that in here to do you calculation. If you do the calculation in the state, it's easiest to test as well.

2023-04-12 09:57 UTC, vithushan19 commented on components/resources/quizzes/careerQuiz/career-quiz.tsx
> +      progress: quizData.questions.length,
progress should be a percent between 0 and 100 that you can just pass into the progress bar. Do the calculations in the state management, not in the progress bar view.

2023-04-12 09:57 UTC, vithushan19 commented on components/resources/quizzes/shared/SkillSelection.test.tsx
> +      quizViewState={quizViewState}
sounds good, feel free to send me a loom if you get stuck

2023-04-14 19:32 UTC, LuckyHariharan commented on components/resources/quizzes/shared/SkillSelection.test.tsx
> +      quizViewState={quizViewState}
Resolved!

2023-04-27 16:10 UTC, closed without merging