Put up Blog #2 - Coding Academy Survival Guide
skillify-ca/skillify-web pull request #943
Opened 2023-04-14 02:35 UTC by LuckyHariharan

In this PR i put up my coding academy survival guide with 18 curated tips. for some reason im struggling to get the numbers from the numbered-list li tag to be on the same row as the text, it seems to only appear above the text. this is why ive not numbered the list yet.

2023-04-18 19:08 UTC, vithushan19 requested changes
can you add your blog posts to sitemap.xml as well, so that google can find them.

2023-05-01 23:51 UTC, LuckyHariharan commented on public/sitemap.xml
>      <url>
updated sitemap for google

2023-05-01 23:52 UTC, LuckyHariharan commented
> can you add your blog posts to sitemap.xml as well, so that google can find them.

@vithushan19 just pushed the sitemap change, ready for review

2023-05-02 13:55 UTC, vithushan19 approved these changes
This is a great post, nice work. I think this will help explain to people what you can learn from Skillify. I think you can also add your name and linkedin profile if you think it'll help in marketing yourself as a strong/communicative developer.

2023-05-02 13:55 UTC, vithushan19 commented on pages/blog/coding-academy-tips.tsx
> +        <div className="mt-4 FLEX">
why do all of these have FLEX capitalized? do you even need these to be flex?

2023-05-02 14:13 UTC, LuckyHariharan commented
> This is a great post, nice work. I think this will help explain to people what you can learn from Skillify. I think you can also add your name and linkedin profile if you think it'll help in marketing yourself as a strong/communicative developer.

ty for your reply, will add my details!

2023-05-05 10:29 UTC, merged