CareerQuiz Back End Logic
skillify-ca/skillify-web pull request #951
Opened 2023-04-25 11:14 UTC by LuckyHariharan

In this PR, I've setup the Backend Logic for the Career-Quiz so that:

- Starting the quiz immediately saves the users name and email
- Reaching the results stage of the quiz updates the row, with the user selections
- Going back to re-complete forms updates the same row
- (Fixed handler to allow maxselection functionality)

2023-04-25 11:32 UTC, LuckyHariharan commented on components/resources/quizzes/shared/StartQuiz.tsx
> +    const { name, value } = event.target;
save the users name and email in state as soon as they enter it

2023-04-25 11:32 UTC, LuckyHariharan commented on components/resources/quizzes/careerQuiz/career-quiz.tsx
> +    const currentQuestion =
updated handler to implement max selections

2023-04-25 11:32 UTC, LuckyHariharan commented on components/resources/quizzes/careerQuiz/career-quiz.tsx
> +    const finalResponseObject = [
final response object used to pass user selections to the upsert mutation

2023-04-25 11:33 UTC, LuckyHariharan commented on components/resources/quizzes/careerQuiz/career-quiz.tsx
> +  title: quizData.title,
initialize quiz to remove unnecessary useEffect

2023-04-25 16:04 UTC, iamnotreddy requested changes
nice work! i think we can clean up the max selection logic, check out my approach below in the comments

One UI comment:
- let's just have it say "Select your highest level of education"
![Screen Shot 2023-04-25 at 10 32 08 AM](https://user-images.githubusercontent.com/98791180/234310134-be334255-d180-40d7-8f14-95724f640295.png)

2023-04-25 16:04 UTC, iamnotreddy commented on components/resources/quizzes/careerQuiz/career-quiz.tsx
> +    if (maxSelection === 1) {
i think this logic is too long and a little over-complicated.. i played around with some code and got a simpler approach very close to working

check my suggestion and lmk if i'm overlooking something: 
- move the optional maxSelections prop to the QuizQuestionViewState type
- change how you're initializing the quiz view state so it accounts for this type change
- now you can access maxSelections in the skillSelections prop
- change the answer selection from a div to a button so you have access to the disabled prop
- store the number of questions selected in a local state and increment / decrement inside your handle click
```
const handleClick = (option: QuizOptionViewState) => {
    handleOptionClick(option);
    option.isSelected
      ? setNumOptionsSelected((prev) => prev - 1)
      : setNumOptionsSelected((prev) => prev + 1);
  };
```
- disable the button if num questions selected greater than max selections  
```
disabled={numOptionsSelected >= maxSelections && !option.isSelected}
```

only thing i didn't fully figure out was resetting the state when you switch to a different question

2023-04-25 16:04 UTC, iamnotreddy commented on components/resources/quizzes/careerQuiz/career-quiz.tsx
> +  const [saveUserPreferences] = useMutation(UPSERT_CAREER_QUIZ_RESPONSE);
check the comment I left on Jimi's PR but we only need the below mutation function and we can call it saveQuizResponse

you'll still have two handlers though

2023-04-26 20:52 UTC, vithushan19 commented on components/resources/quizzes/shared/BluePrint.tsx
> +  const result = "Software Engineer";
we don't career quiz specific logic in the shared components

2023-04-26 20:52 UTC, vithushan19 commented on components/resources/quizzes/shared/BluePrint.tsx
> +            handleQuizResponseMutations(quizViewState, result);
can we just make this function part of the `onNextClick` function that's passed in from the parent?

2023-04-27 18:14 UTC, iamnotreddy approved these changes
as we discussed, im good with this if vithushan is

2023-04-28 11:46 UTC, merged